trigger:
- master

pool:
 vmImage: "ubuntu-latest"

jobs:
- job: Job1
  steps:
  - script: echo Job1!
    displayName: 'Run a online script for Job1'  
  - script: |
      echo Add other tasks to build, test, and deploy.
      echo See my work
      echo Hello World2

- job: Job2
  dependsOn: Job1
  steps:
  - script: echo Job2!
    displayName: 'Run a online script for Job2'  

- job: Job3
  dependsOn: Job1
  steps:
  - script: echo Job3!
    displayName: 'Run a online script for Job3'  

- job: Job4
  dependsOn: 
  - Job1
  - Job2
  - Job3
  steps:
  - script: echo Job3!
    displayName: 'Run a online script for Job4'  
   
  




